## Pandas Dataframes

- A DataFrame is a 2-dimensional, size-mutable, and heterogeneous tabular data structure with labeled axes (rows and columns). It is primarily used for data manipulation, cleaning, and analysis in languages like Python
- Conceptually, a DataFrame is similar to an Excel spreadsheet or a SQL table, where each column represents a variable and each row represents an observation. 
- Single column is a Series
- Single row is called as "B-Series"

In [80]:
import pandas as pd
import numpy as np

### Creating Dataframes

In [81]:
# using lists 
# iq,marks,package of students

student_data = [
    [70,80,7],
    [90,97,10],
    [80,60,3]
]
student_data_idx = ["IQ","Marks","Salary"]

pd.DataFrame(student_data,columns=student_data_idx)

   IQ  Marks  Salary
0  70     80       7
1  90     97      10
2  80     60       3

In [82]:
# using dictonaries
student_data = {
    "name" : ['Raju','Rupa','Divya','Laura','Suma'],
    "iq" : [100,80,50,0,0],
    "marks" : [90,70,60,0,0],
    "package" : [10,7,4,0,0]
}
student_dataset = pd.DataFrame(student_data)
student_dataset = student_dataset.set_index('name')
student_dataset

        iq  marks  package
name
Raju   100     90       10
Rupa    80     70        7
Divya   50     60        4
Laura    0      0        0
Suma     0      0        0

In [83]:
# using read_csv
movies = pd.read_csv("./movies.csv")

In [84]:
movies

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1624,Tera Mera Saath Rahen,tt0301250,https://upload.wikimedia.org/wikipedia/en/2/2b...,https://en.wikipedia.org/wiki/Tera_Mera_Saath_...,Tera Mera Saath Rahen,Tera Mera Saath Rahen,0,2001,148,Drama,4.9,278,Raj Dixit lives with his younger brother Rahu...,A man is torn between his handicapped brother ...,NaN,Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...,NaN,7 November 2001 (India)
1625,Yeh Zindagi Ka Safar,tt0298607,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Yeh_Zindagi_Ka_S...,Yeh Zindagi Ka Safar,Yeh Zindagi Ka Safar,0,2001,146,Drama,3.0,133,Hindi pop-star Sarina Devan lives a wealthy ...,A singer finds out she was adopted when the ed...,NaN,Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...,NaN,16 November 2001 (India)
1626,Sabse Bada Sukh,tt0069204,NaN,https://en.wikipedia.org/wiki/Sabse_Bada_Sukh,Sabse Bada Sukh,Sabse Bada Sukh,0,2018,\N,Comedy|Drama,6.1,13,Village born Lalloo re-locates to Bombay and ...,Village born Lalloo re-locates to Bombay and ...,NaN,Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...,NaN,NaN
1627,Daaka,tt10833860,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Daaka,Daaka,Daaka,0,2019,136,Action,7.4,38,Shinda tries robbing a bank so he can be wealt...,Shinda tries robbing a bank so he can be wealt...,NaN,Gippy Grewal|Zareen Khan|,NaN,1 November 2019 (USA)
1628,Humsafar,tt2403201,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Humsafar,Humsafar,Humsafar,0,2011,35,Drama|Romance,9.0,2968,Sara and Ashar are childhood friends who share...,Ashar and Khirad are forced to get married due...,NaN,Fawad Khan|,NaN,TV Series (2011–2012)

In [85]:
# ipl dataset
ipl = pd.read_csv("./ipl-matches.csv")
ipl

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,335986,Kolkata,2008-04-20,2007/08,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper
947,335984,Delhi,2008-04-19,2007/08,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

### DataFrame Attributes and Methods

In [86]:
# shape
movies.shape

(1629, 18)

In [87]:
# dtype
movies.dtypes

title_x              object
imdb_id              object
poster_path          object
wiki_link            object
title_y              object
original_title       object
is_adult              int64
year_of_release       int64
runtime              object
genres               object
imdb_rating         float64
imdb_votes            int64
story                object
summary              object
tagline              object
actors               object
wins_nominations     object
release_date         object
dtype: object

In [88]:
# index
movies.index

RangeIndex(start=0, stop=1629, step=1)

In [89]:
# columns
movies.columns

Index(['title_x', 'imdb_id', 'poster_path', 'wiki_link', 'title_y',
       'original_title', 'is_adult', 'year_of_release', 'runtime', 'genres',
       'imdb_rating', 'imdb_votes', 'story', 'summary', 'tagline', 'actors',
       'wins_nominations', 'release_date'],
      dtype='object')

In [90]:
# values
movies.values

array([['Uri: The Surgical Strike', 'tt8291224',
        'https://upload.wikimedia.org/wikipedia/en/thumb/3/3b/URI_-_New_poster.jpg/220px-URI_-_New_poster.jpg',
        ...,
        'Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Gautam|Kirti Kulhari|Rajit Kapoor|Ivan Rodrigues|Manasi Parekh|Swaroop Sampat|Riva Arora|Yogesh Soman|Fareed Ahmed|Akashdeep Arora|Kallol Banerjee|',
        '4 wins', '11 January 2019 (USA)'],
       ['Battalion 609', 'tt9472208', nan, ...,
        'Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elena Kazan|Vishwas Kini|Major Kishore|Jashn Kohli|Rammy C. Pandey|Manish Sharma|Sparsh Sharma|Farnaz Shetty|Vikas Shrivastav|Chandraprakash Thakur|Brajesh Tiwari|',
        nan, '11 January 2019 (India)'],
       ['The Accidental Prime Minister (film)', 'tt6986710',
        'https://upload.wikimedia.org/wikipedia/en/thumb/a/a1/The_Accidental_Prime_Minister_film.jpg/220px-The_Accidental_Prime_Minister_film.jpg',
        ...,
        'Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul Sharma|Manoj Anand|Arjun Mathur|Suzanne Bernert|Abdul Quadir Amin|Bharat Mistri|Divya Seth|Anil Rastogi|Ramesh Bhatkar|Parrgash Kaur|Jess Kaur|',
        nan, '11 January 2019 (USA)'],
       ...,
       ['Sabse Bada Sukh', 'tt0069204', nan, ...,
        'Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpal Dutt|Meeta Faiyyaz|Rabi Ghosh|Tarun Ghosh|Sanjeev Kumar|Keshto Mukherjee|Meena Rai|',
        nan, nan],
       ['Daaka', 'tt10833860',
        'https://upload.wikimedia.org/wikipedia/en/thumb/4/45/Daaka.jpg/220px-Daaka.jpg',
        ..., 'Gippy Grewal|Zareen Khan|', nan, '1 November 2019 (USA)'],
       ['Humsafar', 'tt2403201',
        'https://upload.wikimedia.org/wikipedia/en/thumb/4/41/Flag_of_India.svg/23px-Flag_of_India.svg.png',
        ..., 'Fawad Khan|', nan, 'TV Series (2011–2012)']],
      shape=(1629, 18), dtype=object)

In [91]:
# head and tail
movies.head(2)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)

In [92]:
movies.tail(2)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
1627,Daaka,tt10833860,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Daaka,Daaka,Daaka,0,2019,136,Action,7.4,38,Shinda tries robbing a bank so he can be wealt...,Shinda tries robbing a bank so he can be wealt...,NaN,Gippy Grewal|Zareen Khan|,NaN,1 November 2019 (USA)
1628,Humsafar,tt2403201,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Humsafar,Humsafar,Humsafar,0,2011,35,Drama|Romance,9.0,2968,Sara and Ashar are childhood friends who share...,Ashar and Khirad are forced to get married due...,NaN,Fawad Khan|,NaN,TV Series (2011–2012)

In [93]:
# sample
ipl.sample(4)

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
256,1136618,Kolkata,2018-05-23,2018,Eliminator,Kolkata Knight Riders,Rajasthan Royals,Eden Gardens,Rajasthan Royals,field,N,Kolkata Knight Riders,Runs,25.0,NaN,AD Russell,"['SP Narine', 'CA Lynn', 'RV Uthappa', 'N Rana...","['AM Rahane', 'RA Tripathi', 'SV Samson', 'H K...",AK Chaudhary,Nitin Menon
97,1254097,Abu Dhabi,2021-09-25,2021,36,Delhi Capitals,Rajasthan Royals,"Zayed Cricket Stadium, Abu Dhabi",Rajasthan Royals,field,N,Delhi Capitals,Runs,33.0,NaN,SS Iyer,"['PP Shaw', 'S Dhawan', 'SS Iyer', 'RR Pant', ...","['LS Livingstone', 'YBK Jaiswal', 'SV Samson',...",CB Gaffaney,UV Gandhe
50,1304070,Mumbai,2022-04-14,2022,24,Gujarat Titans,Rajasthan Royals,"Dr DY Patil Sports Academy, Mumbai",Rajasthan Royals,field,N,Gujarat Titans,Runs,37.0,NaN,HH Pandya,"['MS Wade', 'Shubman Gill', 'V Shankar', 'HH P...","['JC Buttler', 'D Padikkal', 'R Ashwin', 'SV S...",CB Gaffaney,R Pandit
486,829715,Delhi,2015-04-12,2015,6,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,field,N,Rajasthan Royals,Wickets,3.0,NaN,DJ Hooda,"['MA Agarwal', 'SS Iyer', 'JP Duminy', 'Yuvraj...","['AM Rahane', 'SV Samson', 'SPD Smith', 'KK Na...",SD Fry,CB Gaffaney

In [94]:
# info
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1629 entries, 0 to 1628
Data columns (total 18 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   title_x           1629 non-null   object
 1   imdb_id           1629 non-null   object
 2   poster_path       1526 non-null   object
 3   wiki_link         1629 non-null   object
 4   title_y           1629 non-null   object
 5   original_title    1629 non-null   object
 6   is_adult          1629 non-null   int64
 7   year_of_release   1629 non-null   int64
 8   runtime           1629 non-null   object
 9   genres            1629 non-null   object
 10  imdb_rating       1629 non-null   float64
 11  imdb_votes        1629 non-null   int64
 12  story             1609 non-null   object
 13  summary           1629 non-null   object
 14  tagline           557 non-null    object
 15  actors            1624 non-null   object
 16  wins_nominations  707 non-null    object
 17  release_date      1522 non-null   object
dtypes: float64(1), int64(3), object(14)
memory usage: 229.2+ KB

In [95]:
# describe -> gives a mathamtical summary
movies.describe()

       is_adult  year_of_release  imdb_rating     imdb_votes
count    1629.0      1629.000000  1629.000000    1629.000000
mean        0.0      2010.263966     5.557459    5384.263352
std         0.0         5.381542     1.567609   14552.103231
min         0.0      2001.000000     0.000000       0.000000
25%         0.0      2005.000000     4.400000     233.000000
50%         0.0      2011.000000     5.600000    1000.000000
75%         0.0      2015.000000     6.800000    4287.000000
max         0.0      2019.000000     9.400000  310481.000000

In [96]:
ipl.describe()

                 ID      Margin
count  9.500000e+02  932.000000
mean   8.304852e+05   17.056867
std    3.375678e+05   21.633109
min    3.359820e+05    1.000000
25%    5.012612e+05    6.000000
50%    8.297380e+05    8.000000
75%    1.175372e+06   19.000000
max    1.312200e+06  146.000000

In [97]:
# isnull
movies.isnull().sum()

title_x                0
imdb_id                0
poster_path          103
wiki_link              0
title_y                0
original_title         0
is_adult               0
year_of_release        0
runtime                0
genres                 0
imdb_rating            0
imdb_votes             0
story                 20
summary                0
tagline             1072
actors                 5
wins_nominations     922
release_date         107
dtype: int64

In [98]:
# duplicated
movies.duplicated().sum()

np.int64(0)

In [99]:
student_dataset.duplicated().sum()

np.int64(1)

In [100]:
# rename
student_dataset

        iq  marks  package
name
Raju   100     90       10
Rupa    80     70        7
Divya   50     60        4
Laura    0      0        0
Suma     0      0        0

In [101]:
student_dataset.rename(columns={'marks':'percent','package':'lpa'}, inplace=True)
student_dataset

        iq  percent  lpa
name
Raju   100       90   10
Rupa    80       70    7
Divya   50       60    4
Laura    0        0    0
Suma     0        0    0

### Math Methods

In [102]:
student_dataset

        iq  percent  lpa
name
Raju   100       90   10
Rupa    80       70    7
Divya   50       60    4
Laura    0        0    0
Suma     0        0    0

In [103]:
# sum 
# column wise
student_dataset.sum()

iq         230
percent    220
lpa         21
dtype: int64

In [104]:
# row wise operations 
student_dataset.sum(axis=1)

name
Raju     200
Rupa     157
Divya    114
Laura      0
Suma       0
dtype: int64

In [105]:
# mean
student_dataset.mean()

iq         46.0
percent    44.0
lpa         4.2
dtype: float64

In [106]:
# min 
student_dataset.min()

iq         0
percent    0
lpa        0
dtype: int64

In [107]:
# max
student_dataset.max()

iq         100
percent     90
lpa         10
dtype: int64

In [108]:
# variance
student_dataset.var()

iq         2080.0
percent    1730.0
lpa          19.2
dtype: float64

In [109]:
# standard deviation
student_dataset.std()

iq         45.607017
percent    41.593269
lpa         4.381780
dtype: float64

In [110]:
# median
student_dataset.median()

iq         50.0
percent    60.0
lpa         4.0
dtype: float64

### Selecting Columns from DataFrame

In [111]:
# single column
# returns a series

# movie title series
movies["title_x"]

0                   Uri: The Surgical Strike
1                              Battalion 609
2       The Accidental Prime Minister (film)
3                            Why Cheat India
4                            Evening Shadows
                        ...
1624                   Tera Mera Saath Rahen
1625                    Yeh Zindagi Ka Safar
1626                         Sabse Bada Sukh
1627                                   Daaka
1628                                Humsafar
Name: title_x, Length: 1629, dtype: object

In [112]:
# multiple cols
# returns a DataFrame

# movie title, actors, year
movies[['title_x','actors','year_of_release']]

,title_x,actors,year_of_release
0,Uri: The Surgical Strike,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,2019
1,Battalion 609,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,2019
2,The Accidental Prime Minister (film),Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,2019
3,Why Cheat India,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,2019
4,Evening Shadows,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,2018
...,...,...,...
1624,Tera Mera Saath Rahen,Ajay Devgn|Sonali Bendre|Namrata Shirodkar|Pre...,2001
1625,Yeh Zindagi Ka Safar,Ameesha Patel|Jimmy Sheirgill|Nafisa Ali|Gulsh...,2001
1626,Sabse Bada Sukh,Vijay Arora|Asrani|Rajni Bala|Kumud Damle|Utpa...,2018
1627,Daaka,Gippy Grewal|Zareen Khan|,2019
1628,Humsafar,Fawad Khan|,2011

In [113]:
# ipl team1, team1, win
ipl[['Team1','Team2','WinningTeam']]

,Team1,Team2,WinningTeam
0,Rajasthan Royals,Gujarat Titans,Gujarat Titans
1,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals
2,Royal Challengers Bangalore,Lucknow Super Giants,Royal Challengers Bangalore
3,Rajasthan Royals,Gujarat Titans,Gujarat Titans
4,Sunrisers Hyderabad,Punjab Kings,Punjab Kings
...,...,...,...
945,Kolkata Knight Riders,Deccan Chargers,Kolkata Knight Riders
946,Mumbai Indians,Royal Challengers Bangalore,Royal Challengers Bangalore
947,Delhi Daredevils,Rajasthan Royals,Delhi Daredevils
948,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings
949,Royal Challengers Bangalore,Kolkata Knight Riders,Kolkata Knight Riders

### Selecting a Row from DataFrame

- .iloc() searches using index positions
- .loc() seraches using index labels

In [114]:
# single row
movies.iloc[0]

title_x                                      Uri: The Surgical Strike
imdb_id                                                     tt8291224
poster_path         https://upload.wikimedia.org/wikipedia/en/thum...
wiki_link           https://en.wikipedia.org/wiki/Uri:_The_Surgica...
title_y                                      Uri: The Surgical Strike
original_title                               Uri: The Surgical Strike
is_adult                                                            0
year_of_release                                                  2019
runtime                                                           138
genres                                               Action|Drama|War
imdb_rating                                                       8.4
imdb_votes                                                      35112
story               Divided over five chapters  the film chronicle...
summary             Indian army special forces execute a covert op...
tagline                                                           NaN
actors              Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...
wins_nominations                                               4 wins
release_date                                    11 January 2019 (USA)
Name: 0, dtype: object

In [115]:
# multiple rows
movies.iloc[:5]

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India)
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA)
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Why_Cheat_India,Why Cheat India,Why Cheat India,0,2019,121,Crime|Drama,6.0,1891,The movie focuses on existing malpractices in ...,The movie focuses on existing malpractices in ...,NaN,Emraan Hashmi|Shreya Dhanwanthary|Snighdadeep ...,NaN,18 January 2019 (USA)
4,Evening Shadows,tt6028796,NaN,https://en.wikipedia.org/wiki/Evening_Shadows,Evening Shadows,Evening Shadows,0,2018,102,Drama,7.3,280,While gay rights and marriage equality has bee...,Under the 'Evening Shadows' truth often plays...,NaN,Mona Ambegaonkar|Ananth Narayan Mahadevan|Deva...,17 wins & 1 nomination,11 January 2019 (India)

In [116]:
# fancy indexing
movies.iloc[[0,5,100]]

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA)
5,Soni (film),tt6078866,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Soni_(film),Soni,Soni,0,2018,97,Drama,7.2,1595,Soni a young policewoman in Delhi and her su...,While fighting crimes against women in Delhi ...,NaN,Geetika Vidya Ohlyan|Saloni Batra|Vikas Shukla...,3 wins & 5 nominations,18 January 2019 (USA)
100,October (2018 film),tt7700730,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/October_(2018_film),October,October,0,2018,115,Drama|Romance,7.5,11125,Dan (Varun Dhawan) is living the life of any c...,A group of interns are going through the usual...,This is not a love story. This is a story abou...,Varun Dhawan|Banita Sandhu|Gitanjali Rao|Sahil...,3 wins & 9 nominations,13 April 2018 (USA)

In [117]:
# loc 

student_dataset

        iq  percent  lpa
name
Raju   100       90   10
Rupa    80       70    7
Divya   50       60    4
Laura    0        0    0
Suma     0        0    0

In [118]:
# single row
student_dataset.loc["Raju"]

iq         100
percent     90
lpa         10
Name: Raju, dtype: int64

In [119]:
# multiple rows
student_dataset.loc["Raju":"Laura"]

        iq  percent  lpa
name
Raju   100       90   10
Rupa    80       70    7
Divya   50       60    4
Laura    0        0    0

In [120]:
# fancy indexing
student_dataset.loc[['Raju','Laura','Divya']]

        iq  percent  lpa
name
Raju   100       90   10
Laura    0        0    0
Divya   50       60    4

### Selcting both Rows and columns

In [121]:
movies.iloc[0:3,0:3]

,title_x,imdb_id,poster_path
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...
1,Battalion 609,tt9472208,NaN
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...

In [122]:
movies.loc[:5,"title_x":"poster_path"]

,title_x,imdb_id,poster_path
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...
1,Battalion 609,tt9472208,NaN
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...
3,Why Cheat India,tt8108208,https://upload.wikimedia.org/wikipedia/en/thum...
4,Evening Shadows,tt6028796,NaN
5,Soni (film),tt6078866,https://upload.wikimedia.org/wikipedia/en/thum...

### Filtering a DataFrame

In [123]:
ipl.iloc[0:2]

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon

In [124]:
# find all the winners

ipl[ipl['MatchNumber'] == "Final"][['Season','WinningTeam']]

      Season            WinningTeam
0       2022         Gujarat Titans
74      2021    Chennai Super Kings
134  2020/21         Mumbai Indians
194     2019         Mumbai Indians
254     2018    Chennai Super Kings
314     2017         Mumbai Indians
373     2016    Sunrisers Hyderabad
433     2015         Mumbai Indians
492     2014  Kolkata Knight Riders
552     2013         Mumbai Indians
628     2012  Kolkata Knight Riders
702     2011    Chennai Super Kings
775  2009/10    Chennai Super Kings
835     2009        Deccan Chargers
892  2007/08       Rajasthan Royals

In [125]:
# how many super over finishes have occured
ipl[ipl["SuperOver"] == "Y"].shape[0]

14

In [126]:
# how many matches have CSK won in Kolkata
ipl.loc[(ipl["City"] == "Kolkata") & (ipl["WinningTeam"] == "Chennai Super Kings")][["City","WinningTeam"]]

        City          WinningTeam
224  Kolkata  Chennai Super Kings
602  Kolkata  Chennai Super Kings
641  Kolkata  Chennai Super Kings
827  Kolkata  Chennai Super Kings
908  Kolkata  Chennai Super Kings

In [127]:
# how many matches have CSK won in Kolkata(clean)
matches_in_kolkata = ipl["City"] == "Kolkata"
csk_wins = ipl["WinningTeam"] == "Chennai Super Kings"
csk_wins_kolkata = ipl[(matches_in_kolkata) & (csk_wins)]
print(f"CSK wins in Kolkata: {csk_wins_kolkata.shape[0]}")

CSK wins in Kolkata: 5

In [128]:
# toss winner is match winner in percentage
toss_winner = ipl["TossWinner"]
match_winner = ipl["WinningTeam"]
toss_and_match_winners = ipl[toss_winner == match_winner]

percentage_of_toss_and_match_winners = (toss_and_match_winners.shape[0]/ipl.shape[0])*100
print(f"Toss winner is match winner in percentage: {percentage_of_toss_and_match_winners}")

Toss winner is match winner in percentage: 51.473684210526315

In [129]:
# movies with rating higher than 8 and votes>10000

movies_rate_ht_8 = movies["imdb_rating"] > 8.0
movies_with_gt_10k_votes = movies["imdb_votes"] > 10000
movies_rating_gt_8_votes_gt_10k = movies[(movies_rate_ht_8) & (movies_with_gt_10k_votes)]
movies_rating_gt_8_votes_gt_10k[["title_x","imdb_rating","imdb_votes"]]

                          title_x  imdb_rating  imdb_votes
0        Uri: The Surgical Strike          8.4       35112
11                      Gully Boy          8.2       22440
37              Article 15 (film)          8.3       13417
40                Super 30 (film)          8.2       13972
143                       Tumbbad          8.2       16535
146                     Andhadhun          8.4       51615
325              Pink (2016 film)          8.2       33902
354                 Dangal (film)          8.4      131338
418                        Masaan          8.1       19904
426          Drishyam (2015 film)          8.2       58340
436                 Talvar (film)          8.2       26612
469             Queen (2014 film)          8.2       56406
536                 Haider (film)          8.1       46912
566                   Ugly (film)          8.1       17483
567                     PK (film)          8.1      143605
589                  Vishwaroopam          8.2       38016
612            Bhaag Milkha Bhaag          8.2       56205
638                 Shahid (film)          8.3       13537
668       Paan Singh Tomar (film)          8.2       29994
669                       Kahaani          8.1       53181
693            Gangs of Wasseypur          8.2       71636
694   Gangs of Wasseypur – Part 2          8.2       71636
709                        Barfi!          8.1       70443
714              OMG – Oh My God!          8.2       46072
778      Zindagi Na Milegi Dobara          8.1       60826
869             Udaan (2010 film)          8.2       39567
912                      3 Idiots          8.4      310481
930                 Gulaal (film)          8.1       12799
1058     Black Friday (2007 film)          8.5       16761
1066               Chak De! India          8.2       68421
1127             Taare Zameen Par          8.4      148498
1180             Khosla Ka Ghosla          8.3       20538
1183         Lage Raho Munna Bhai          8.1       39486
1188           Omkara (2006 film)          8.1       17594
1195              Rang De Basanti          8.2      103071
1223            Black (2005 film)          8.2       31658
1252                 Iqbal (film)          8.1       14864
1384                       Swades          8.2       76737
1403          Munna Bhai M.B.B.S.          8.1       67148
1554   The Legend of Bhagat Singh          8.1       13455
1567                       Lagaan          8.1       95686
1568                       Lagaan          8.1       95686
1571               Dil Chahta Hai          8.1       62313

#### To filter for movies that contain "Action" within a string that also contains other genres (e.g., "Action|Drama|War"), you should use the Pandas .str.contains() method instead of the equality operator (==).

In [130]:
# action movies with rating higher than 7.5
action_movies = movies["genres"].str.contains("Action",na=False)
movies_above_7_5 = movies["imdb_rating"] > 7.5
movies[(action_movies) & (movies_above_7_5)][["title_x","genres","imdb_rating"]]

                            title_x                   genres  imdb_rating
0          Uri: The Surgical Strike         Action|Drama|War          8.4
41             Family of Thakurganj             Action|Drama          9.4
84                        Mukkabaaz       Action|Drama|Sport          8.1
106                           Raazi    Action|Drama|Thriller          7.8
110   Parmanu: The Story of Pokhran     Action|Drama|History          7.7
112         Bhavesh Joshi Superhero             Action|Drama          7.6
169                The Ghazi Attack      Action|Thriller|War          7.6
219                Raag Desh (film)     Action|Drama|History          8.3
258                   Irudhi Suttru       Action|Drama|Sport          7.6
280                       Laal Rang       Action|Crime|Drama          8.0
297                     Udta Punjab       Action|Crime|Drama          7.8
354                   Dangal (film)   Action|Biography|Drama          8.4
362               Bajrangi Bhaijaan      Action|Comedy|Drama          8.0
365          Baby (2015 Hindi film)          Action|Thriller          8.0
393      Detective Byomkesh Bakshy!  Action|Mystery|Thriller          7.6
449               Titli (2014 film)    Action|Drama|Thriller          7.6
536                   Haider (film)       Action|Crime|Drama          8.1
589                    Vishwaroopam          Action|Thriller          8.2
625                     Madras Cafe    Action|Drama|Thriller          7.7
668         Paan Singh Tomar (film)   Action|Biography|Crime          8.2
693              Gangs of Wasseypur      Action|Comedy|Crime          8.2
694     Gangs of Wasseypur – Part 2      Action|Comedy|Crime          8.2
982                    Jodhaa Akbar     Action|Drama|History          7.6
1039               1971 (2007 film)         Action|Drama|War          7.9
1058       Black Friday (2007 film)       Action|Crime|Drama          8.5
1188             Omkara (2006 film)       Action|Crime|Drama          8.1
1293             Sarkar (2005 film)       Action|Crime|Drama          7.6
1294                          Sehar       Action|Crime|Drama          7.8
1361                 Lakshya (film)     Action|Drama|Romance          7.9
1432                      Gangaajal       Action|Crime|Drama          7.8
1495                 Company (film)       Action|Crime|Drama          8.0
1554     The Legend of Bhagat Singh   Action|Biography|Drama          8.1
1607        Nayak (2001 Hindi film)    Action|Drama|Thriller          7.8

In [131]:
# write a function that can return the track record of  2 teams against each other
def track_record(team1,team2):
    matches = ipl[((ipl["Team1"] == team1) & (ipl["Team2"] == team2)) | 
                 ((ipl["Team1"] == team2) & (ipl["Team2"] == team1))]
    if matches.empty:
        return f'No matches were played between {team1} and {team2}.'
    team1_wins = matches[matches["WinningTeam"] == team1].shape[0]
    team2_wins = matches[matches["WinningTeam"] == team2].shape[0]
    total_matches = matches.shape[0]

    result = {"total_matches":total_matches,
              "team1_wins":team1_wins, 
              "team2_wins":team2_wins}
    return result

def get_record(team1,team2):
    records = track_record(team1,team2)
    print(f"Total matches : {records["total_matches"]}\n{team1} Wins: {records["team1_wins"]}\n{team2} Wins: {records["team2_wins"]}")
    
team1 = "Royal Challengers Bangalore"
team2 = "Mumbai Indians"
get_record(team1,team2)

Total matches : 30
Royal Challengers Bangalore Wins: 13
Mumbai Indians Wins: 17

### Adding new cols

In [132]:
# adding fresh new col
movies["Country"] = "India"
movies.head(3)

,title_x,imdb_id,poster_path,wiki_link,title_y,original_title,is_adult,year_of_release,runtime,genres,imdb_rating,imdb_votes,story,summary,tagline,actors,wins_nominations,release_date,Country
0,Uri: The Surgical Strike,tt8291224,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/Uri:_The_Surgica...,Uri: The Surgical Strike,Uri: The Surgical Strike,0,2019,138,Action|Drama|War,8.4,35112,Divided over five chapters the film chronicle...,Indian army special forces execute a covert op...,NaN,Vicky Kaushal|Paresh Rawal|Mohit Raina|Yami Ga...,4 wins,11 January 2019 (USA),India
1,Battalion 609,tt9472208,NaN,https://en.wikipedia.org/wiki/Battalion_609,Battalion 609,Battalion 609,0,2019,131,War,4.1,73,The story revolves around a cricket match betw...,The story of Battalion 609 revolves around a c...,NaN,Vicky Ahuja|Shoaib Ibrahim|Shrikant Kamat|Elen...,NaN,11 January 2019 (India),India
2,The Accidental Prime Minister (film),tt6986710,https://upload.wikimedia.org/wikipedia/en/thum...,https://en.wikipedia.org/wiki/The_Accidental_P...,The Accidental Prime Minister,The Accidental Prime Minister,0,2019,112,Biography|Drama,6.1,5549,Based on the memoir by Indian policy analyst S...,Explores Manmohan Singh's tenure as the Prime ...,NaN,Anupam Kher|Akshaye Khanna|Aahana Kumra|Atul S...,NaN,11 January 2019 (USA),India

In [133]:
# fillin up NaN / Missing values 
movies["actors"].fillna("Unknown",inplace=True)

In [134]:
# adding cols from existing cols

movie_lead = movies["actors"].str.split("|").apply(lambda x:x[0])
movies["lead_actor"] = movie_lead
movies["lead_actor"]

0          Vicky Kaushal
1            Vicky Ahuja
2            Anupam Kher
3          Emraan Hashmi
4       Mona Ambegaonkar
              ...
1624          Ajay Devgn
1625       Ameesha Patel
1626         Vijay Arora
1627        Gippy Grewal
1628          Fawad Khan
Name: lead_actor, Length: 1629, dtype: object

### Important DataFrame Functions

In [135]:
ipl[:3]

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough

In [140]:
# astype
ipl.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 950 entries, 0 to 949
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ID               950 non-null    int32
 1   City             899 non-null    category
 2   Date             950 non-null    object
 3   Season           950 non-null    category
 4   MatchNumber      950 non-null    object
 5   Team1            950 non-null    category
 6   Team2            950 non-null    category
 7   Venue            950 non-null    object
 8   TossWinner       950 non-null    category
 9   TossDecision     950 non-null    object
 10  SuperOver        946 non-null    object
 11  WinningTeam      946 non-null    category
 12  WonBy            950 non-null    object
 13  Margin           932 non-null    float64
 14  method           19 non-null     object
 15  Player_of_Match  946 non-null    object
 16  Team1Players     950 non-null    object
 17  Team2Players     950 non-null    object
 18  Umpire1          950 non-null    object
 19  Umpire2          950 non-null    object
dtypes: category(6), float64(1), int32(1), object(12)
memory usage: 110.6+ KB

In [139]:
# changing the datatypes for optimization of data set and to reduce the size of dataset
ipl["ID"] = ipl["ID"].astype("int32")
ipl[["City","Team1","Team2","WinningTeam","Season","TossWinner"]] = ipl[["City","Team1","Team2","WinningTeam","Season","TossWinner"]].astype("category")